#!/bin/bash

##################################
#                                #
#       JUST IMAGE SHORT ID      #
#                                #
##################################

run_level0()
{
 if [[ ! -f ./.hash0 ]]
  then
  docker pull busybox 1> /dev/null 2> /dev/null
  flag_hash=$(docker images busybox --format '{{.ID}}'  | sha512sum | awk '{printf $1}')
  echo -n "$flag_hash" > .hash0
 fi
}

clean_level0()
{
  :
}
